import { Project, Technology } from "../types";

export const PROJECTS: Project[] = [
  /*
  {link: '',
   image: '',
   title: '',
   info: ''
  },
   */
  {
    link: "https://juliakuchina.github.io/babylonjs-house/",
    image: "assets/images/spooky-house.png",
    title: "3D Spooky House",
    info: "Babylon.js, Typescript",
  },
  {
    link: "https://juliakuchina.github.io/credit-card-checker/",
    image: "assets/images/card-checker.png",
    title: "Credit Card Checker",
    info: "React, styled-components",
  },
  {
    link: "https://bit.ly/2Pvb5qs",
    image: "assets/images/solar-app.png",
    title: "Anditi Solar App",
    info: "React, Redux, Leaflet, D3, Jest, Styled Components",
  },
  {
    link: "https://bit.ly/2YZp5yF",
    image: "assets/images/3d-portal.png",
    title: "Anditi 3D Portal",
    info: "React, Redux, three.js, sparce-octree, Jest, Styled Components",
  },
  {
    link: "https://juliakuchina.github.io/data-ui-kit/",
    image: "assets/images/data-ui.png",
    title: "Mock Goggle Analytics",
    info: "Webpack, Gulp, D3, Javascript, PostCss, HTML5, CSS3",
  },
  {
    link: "https://juliakuchina.github.io/doppler-effect/",
    image: "assets/images/doppler-effect.png",
    title: "Doppler Effect Visualisation",
    info: "Maths, Javascript",
  },
  {
    link: "https://codepen.io/JKuchina/full/BRVzYp/",
    image: "assets/images/meteorit.jpg",
    title: "Map Data Across the Globe",
    info: "D3, Javascript, Bootstrap, JSON, SVG, CSS. FreeCodeCamp API.",
  },
  {
    link: "https://codepen.io/JKuchina/pen/XREOWg",
    image: "assets/images/d3-force-directed.jpg",
    title: "D3.js Force Directed Graph",
    info: "D3, Javascript, Bootstrap, SVG, CSS. FreeCodeCamp API.",
  },
  {
    link: "https://codepen.io/JKuchina/pen/GmOgxJ",
    image: "assets/images/d3-heatmap.jpg",
    title: "D3.js Heat Map",
    info: "D3, Javascript, Bootstrap, SVG, CSS. FreeCodeCamp API.",
  },
  {
    link: "https://codepen.io/JKuchina/pen/vmmpve",
    image: "assets/images/d3-scatterplot.jpg",
    title: "D3.js Scatterplot Graph",
    info: "D3, Javascript, Bootstrap, SVG, CSS. FreeCodeCamp API.",
  },
  {
    link: "https://codepen.io/JKuchina/pen/QvddYJ",
    image: "assets/images/d3js-bar-chart.jpg",
    title: "Data Visualization with a Bar Chart",
    info: "D3, Javascript, Bootstrap, SVG, CSS. NIPA API.",
  },
  {
    link: "https://codepen.io/JKuchina/full/zwBaOM/",
    image: "assets/images/gameoflife.jpg",
    title: "Game Of Life",
    info: "React, Javascript, Bootstrap,HTML, SASS, CSS",
  },
  {
    link: "https://codepen.io/JKuchina/pen/RpRzeo",
    image: "assets/images/recipebox.jpg",
    title: "Recipe Box",
    info: "React, Javascript, Bootstrap,HTML, SASS, CSS",
  },
  {
    link: "https://codepen.io/JKuchina/full/vKaPaO/",
    image: "assets/images/simongame.png",
    title: "Simon Game",
    info: "Javascript, jQuery, Bootstrap, HTML, CSS",
  },
  {
    link: "https://codepen.io/JKuchina/full/rLAKwL/",
    image: "assets/images/tictactoe.png",
    title: "Tic Tac Toe Game",
    info: "Javascript, jQuery, Bootstrap, HTML, CSS",
  },
  {
    link: "https://codepen.io/JKuchina/full/akEdwa/",
    image: "assets/images/Pomodoro-Clock.jpg",
    title: "Pomodoro Clock",
    info: "Javascript, jQuery, Bootstrap, HTML, CSS",
  },
  {
    link: "https://codepen.io/JKuchina/full/eZebZJ/",
    image: "assets/images/Calculator.jpg",
    title: "Calculator",
    info: "Javascript, jQuery, Bootstrap, HTML, CSS",
  },
  {
    link: "https://codepen.io/JKuchina/full/XdevWj/",
    image: "assets/images/twitch.jpg",
    title: "Twitch Streamers",
    info: "Javascript, jQuery, Bootstrap, HTML, CSS",
  },
  {
    link: "https://codepen.io/JKuchina/full/PNJezg/",
    image: "assets/images/wiki.jpg",
    title: "Wikipedia Search",
    info: "Javascript, jQuery, JSON, Bootstrap, HTML, CSS.  Open Wikipedia API.",
  },
  {
    link: "https://codepen.io/JKuchina/full/JXrMEp",
    image: "assets/images/weatherapp.jpg",
    title: "Local Weather",
    info: "Javascript, jQuery, JSON, Bootstrap, HTML, CSS.  Open Weather API, Geolocation API.",
  },
  {
    link: "https://codepen.io/JKuchina/full/eZEOea/",
    image: "assets/images/quotemachine.jpg",
    title: "Random Quote Machine",
    info: "Javascript, jQuery, JSON, Bootstrap, HTML, CSS. Random picture API, random quote API.",
  },
];

export const TECHNOLOGIES: Technology[] = [
  { text: "JavaScript", size: 5, group: 1 },
  { text: "Typescript", size: 8, group: 1 },
  { text: "PHP", size: 1, group: 1 },
  { text: "SQL", size: 1, group: 1 },
  { text: "React", size: 6, group: 1 },
  { text: "Redux", size: 3, group: 1 },
  { text: "React hooks", size: 6, group: 1 },
  { text: "Jest", size: 2, group: 1 },

  { text: "Three.js", size: 3, group: 2 },
  { text: "Babylon.js", size: 4, group: 2 },
  { text: "Leaflet.js", size: 3.5, group: 2 },
  { text: "Turf.js", size: 2, group: 2 },
  { text: "D3", size: 1, group: 2 },
  { text: "JQuery", size: 2, group: 2 },

  { text: "styled", size: 5, group: 7 },
  { text: "Material UI", size: 5, group: 7 },
  { text: "Bootstrap", size: 4, group: 7 },
  { text: "SVG", size: 2, group: 7 },
  { text: "PostCSS", size: 3, group: 7 },
  { text: "SASS", size: 2, group: 7 },
  { text: "CSS3", size: 4, group: 7 },
  { text: "HTML5", size: 2, group: 7 },

  { text: "CI-CD", size: 2, group: 3 },
  { text: "Apollo", size: 2, group: 3 },
  { text: "GraphQL", size: 5, group: 3 },
  { text: "REST", size: 4, group: 3 },
  { text: "MySQL", size: 2, group: 4 },
  { text: "Oracle", size: 1.5, group: 4 },
  { text: "Firebase", size: 3, group: 4 },
  { text: "Webpack", size: 3.5, group: 4 },
  { text: "Gulp", size: 1.5, group: 4 },
  { text: "Git", size: 3, group: 4 },
  { text: "SVN", size: 1.5, group: 4 },
  { text: "Jira", size: 1.5, group: 4 },
  { text: "VS", size: 1.5, group: 4 },
  { text: "cPanel", size: 2, group: 4 },
  { text: "Figma", size: 2, group: 4 },
  { text: "Agile", size: 3, group: 4 },
];
